/** Locale dictionary for the desktop About settings section. */
export const DESKTOP_ABOUT_LOCALE_DICTIONARY = {
  zh: {
    nav: '关于',
    title: '关于 DSH Desktop',
    subtitle: 'DeepSeek Harness 的桌面工作台。应用会自动检查稳定版本，下载与安装始终需要用户确认。',
    version: '版本',
    updateMethod: '更新方式',
    confirmedInstall: '自动检测；确认后下载并安装',
    checkUpdates: '检查更新',
    checkingUpdates: '检查中…',
    updateProgress: '更新进度',
    statusChecking: '正在检查稳定版本…',
    statusAvailable: '发现 DSH Desktop {version}',
    statusAwaitingConfirmation: '等待确认下载 DSH Desktop {version}',
    statusDownloading: '正在下载 {percent}% · {received} / {total}',
    statusDownloadingUnknown: '正在下载 · 已接收 {received}',
    statusVerifying: '下载完成，正在校验 DSH Desktop {version}…',
    statusReady: 'DSH Desktop {version} 已校验，等待安装确认',
    statusLaunching: '正在启动 DSH Desktop {version} 安装程序…',
    statusFailed: '更新操作失败。请检查网络和磁盘空间后重试。',
    statusCancelled: '更新已取消；当前版本没有改变。',
    repository: '仓库',
    viewRelease: '查看版本与更新说明',
  },
  en: {
    nav: 'About',
    title: 'About DSH Desktop',
    subtitle: 'A desktop workbench for DeepSeek Harness. Stable releases are checked automatically; download and installation always require confirmation.',
    version: 'Version',
    updateMethod: 'Update method',
    confirmedInstall: 'Automatic checks; confirmed download and install',
    checkUpdates: 'Check for updates',
    checkingUpdates: 'Checking…',
    updateProgress: 'Update progress',
    statusChecking: 'Checking for a stable release…',
    statusAvailable: 'DSH Desktop {version} is available',
    statusAwaitingConfirmation: 'Waiting to confirm the DSH Desktop {version} download',
    statusDownloading: 'Downloading {percent}% · {received} / {total}',
    statusDownloadingUnknown: 'Downloading · {received} received',
    statusVerifying: 'Download complete; verifying DSH Desktop {version}…',
    statusReady: 'DSH Desktop {version} is verified and awaiting install confirmation',
    statusLaunching: 'Launching the DSH Desktop {version} installer…',
    statusFailed: 'The update failed. Check the network and disk space, then retry.',
    statusCancelled: 'The update was cancelled; the installed version did not change.',
    repository: 'Repository',
    viewRelease: 'View release and notes',
  },
} as const
