import type { Context } from '@deepseek-ai/cordis'
import type { Agent } from '@deepseek-ai/dsh-agent'
import { createUserMessage, type ContentBlock } from '@deepseek-ai/dsh-llm'
import { credentialRef, parseCredentialKey } from '@deepseek-ai/dsh-credentials'
import { scopeChainOf } from '@deepseek-ai/dsh-scope'
import { defineTool, type ToolExecution } from '@deepseek-ai/dsh-tools'
import type { ImageAttachmentRef } from '@deepseek-ai/dsh-attachment'
import type {} from '@deepseek-ai/dsh-api-session-controller'
import type {} from '@deepseek-ai/dsh-commands'
import { generateImage, GenerationError, snapshotGenerationRoute, type ImageGenerationRoute, type GenerationAudit } from './generation-broker.ts'

export const GENERATE_IMAGE_TOOL = 'DesktopGenerateImage'
const DENIAL = '受控生成仅允许当前供应商的生图工具；Shell、技能、脚本、MCP、委托和凭据文件访问均被禁止。 / Controlled generation denies all unreviewed tools. No fallback is allowed.'

declare module '@deepseek-ai/dsh-session/types' {
  interface SessionEventMap {
    'desktop/generation-mode': { active: boolean; inherited?: true }
    'desktop/generation-audit': GenerationAudit
  }
}

interface GenerationTask {
  readonly route: Readonly<ImageGenerationRoute>
  readonly chat: Readonly<{ provider: string; model: string }>
  readonly turn: number
  readonly signal: AbortSignal
  readonly abort: AbortController
  used: boolean
}
interface GenerationState { active: boolean; inherited: boolean; task?: GenerationTask | undefined; revokedTurn?: number; lift?: (() => void) | undefined }

/** Convenience routing only. The security boundary is the Host-owned mode plus a deny-by-default tool guard. */
export function looksLikeImageRequest(text: string): boolean {
  return /(?:生(?:成)?[一张幅个些\s]*图(?:片|像)?|画(?:一|个|张|幅|一幅|一张)|绘制.{0,12}(?:图片|图像|插画|海报)|(?:生成|制作).{0,12}(?:图片|图像|插画|海报|壁纸))|\b(?:generate|create|draw|paint|make)\b[\s\S]{0,100}\b(?:image|picture|illustration|poster|wallpaper)\b/iu.test(text)
}

/** Selected route comes from durable user selection, never model tool arguments. */
export function selectedGenerationChat(ctx: Context, agent: Agent): { provider: string; model: string } {
  const state = ctx.get('sessionProjections')?.stateOf(agent.session, 'modelSelection')
  const chosen = state?.pending ?? state?.lastUsed
  const provider = chosen?.provider ?? agent.options.provider
  const model = chosen?.model ?? agent.options.model
  if (!provider || !model) throw new GenerationError('NO_ROUTE', 'Select a chat provider before entering controlled generation.')
  return { provider, model }
}

/** Resolve exactly one user-selected reference or provider API-key record; never search or use ambient grants. */
export async function resolveGenerationCredential(ctx: Context, ref: string): Promise<string | undefined> {
  const credentials = ctx.get('credentials')
  if (!credentials) return undefined
  if (ref.includes('/')) {
    const record = await credentials.readRecord(parseCredentialKey(ref))
    return record?.kind === 'api-key' ? record.key : undefined
  }
  return (await credentials.resolve(credentialRef(ref)))?.value
}

/** Desktop-owned constraints layered over the unmodified Harness tool runtime. */
export class GenerationPolicy {
  private readonly states = new WeakMap<Agent, GenerationState>()
  private readonly liveStates = new Set<GenerationState>()
  private disposed = false
  constructor(private readonly ctx: Context, private readonly routes: () => readonly ImageGenerationRoute[]) {
    ctx.tools.register(defineTool({
      name: GENERATE_IMAGE_TOOL,
      description: 'Generate one image through the Host-authorized provider route. Never retry failures or use another tool/provider. Route, model, endpoint and credentials are Host-owned.',
      parameters: { prompt: { type: 'string', required: true, description: 'Image description only.' } },
      output: {
        schema: { type: 'object', additionalProperties: false, properties: { image: { type: 'json', required: true }, provider: { type: 'string', required: true }, model: { type: 'string', required: true } } },
        render: (_args, value): ContentBlock[] => [
          { type: 'text', text: `Image generated by ${value.provider} / ${value.model}.` },
          { type: 'image', attachment: value.image as unknown as ImageAttachmentRef },
        ],
      },
      execute: async (args, exec) => {
        const agent = exec.agent
        const state = agent && this.states.get(agent), task = state?.task
        if (!agent || !state?.active || !task || this.denial(exec)) throw new GenerationError('DENIED', DENIAL)
        if (Object.keys(args).some(key => key !== 'prompt')) throw new GenerationError('INVALID_ARGS', 'Only an image prompt may be supplied; the route cannot be overridden.')
        task.used = true // An attempted request consumes this turn's authorization, including failures.
        const signal = AbortSignal.any([task.signal, exec.signal])
        const assertCurrent = (): void => {
          signal.throwIfAborted()
          const chat = selectedGenerationChat(ctx, agent)
          if (this.disposed || !state.active || state.task !== task || chat.provider !== task.chat.provider || chat.model !== task.chat.model) {
            throw new GenerationError('STALE_ROUTE', 'The selected route changed. Start a new generation request; no old authorization is reused.')
          }
        }
        assertCurrent()
        const image = await generateImage(task.route, args.prompt, signal, {
          resolveCredential: async ref => {
            assertCurrent()
            const value = await resolveGenerationCredential(ctx, ref)
            assertCurrent()
            return value
          },
          audit: event => { agent.session.append('desktop/generation-audit', event) },
        })
        assertCurrent()
        const attachments = ctx.get('attachments')
        if (!attachments) throw new GenerationError('NO_STORAGE', 'Image attachment storage is unavailable.')
        const ref = await attachments.saveImage({ ...image, name: 'generated-image' })
        assertCurrent()
        agent.session.append('desktop/generation-audit', { capability: 'image', provider: task.route.provider, model: task.route.model,
          destination: new URL(task.route.endpoint).host, authorization: 'user-generation-route', outcome: 'stored' })
        return { image: { ...ref, ...(ref.originalDimensions ? { originalDimensions: { ...ref.originalDimensions } } : {}) }, provider: task.route.provider, model: task.route.model }
      },
    }))

    // Visibility is additive defense. Both early policy and the final monotonic guard are required:
    // extensions may expose scoped tools or return allow from their pre-execute listeners.
    ctx.on('tools/pre-execute', async (exec, next) => {
      if (exec.name === GENERATE_IMAGE_TOOL && exec.agent && !this.owner(exec.agent)) this.enable(exec.agent)
      const reason = this.denial(exec)
      return reason ? { kind: 'deny', reason } : next()
    }, { prepend: true })
    ctx.tools.guard(exec => this.denial(exec))
    ctx.on('system-prompt/assemble', async (_assembly, context, next) => {
      const assembled = await next()
      if (!context.agent || !this.owner(context.agent)) return assembled
      return { ...assembled, tools: assembled.tools.filter(tool => tool.name === GENERATE_IMAGE_TOOL) }
    }, { prepend: true })
    ctx.on('agent/created', ({ agent }) => { this.state(agent); this.inherit(agent) })
    ctx.on('agent/disposed', ({ agent }) => {
      const state = this.states.get(agent)
      state?.task?.abort.abort(); state?.lift?.()
      if (state) this.liveStates.delete(state)
      this.states.delete(agent)
    })
    ctx.on('session/event', (session, event) => {
      const agent = ctx.agents.get(session.id), state = agent && this.states.get(agent)
      if (!state?.task) return
      if (event.type === 'turn/end' || (event.type === 'model/selection' && (event.data.provider !== state.task.chat.provider || event.data.model !== state.task.chat.model))) {
        if (event.type === 'model/selection') state.revokedTurn = state.task.turn
        state.task.abort.abort(); state.task = undefined
      }
    })
    ctx.on('agent/inbox/claimed', ({ agent, message }) => {
      if (message.source.kind === 'user' && message.content.some(block => block.type === 'text' && looksLikeImageRequest(block.text))) this.enable(agent)
    })
    ctx.on('agent/pre-step', async ({ agent, messages, turn, signal }, next) => {
      // Recheck after notification dispatch (notification listener errors cannot veto the loop).
      if (messages.some(message => message.source.kind === 'user' && message.content.some(block => block.type === 'text' && looksLikeImageRequest(block.text)))) this.enable(agent)
      const owner = this.owner(agent)
      if (!owner) return next()
      if (owner !== agent || this.state(agent).inherited) throw new GenerationError('DELEGATION_DENIED', DENIAL)
      const state = this.state(agent)
      if (state.revokedTurn === turn) throw new GenerationError('STALE_ROUTE', 'The image route changed during this turn. Submit a new request to authorize the new route.')
      if (state.task?.turn !== turn) {
        state.task = undefined
        const chat = Object.freeze(selectedGenerationChat(ctx, agent))
        const route = snapshotGenerationRoute(chat.provider, this.routes())
        if (!ctx.get('attachments')) throw new GenerationError('NO_STORAGE', 'Image attachment storage is unavailable; generation has not started.')
        const abort = new AbortController()
        state.task = { route, chat, turn, signal: AbortSignal.any([signal, abort.signal]), abort, used: false }
      }
      signal.throwIfAborted()
      return next()
    }, { prepend: true })
    ctx.on('agent/request', async ({ agent }, next) => {
      const config = await next(), task = this.states.get(agent)?.task
      if (this.owner(agent) && (!task || task.signal.aborted || config.provider !== task.chat.provider || config.model !== task.chat.model)) {
        throw new GenerationError('STALE_ROUTE', 'Controlled generation route changed. Submit a new request.')
      }
      return config
    }, { prepend: true })
    ctx.systemPrompt.section({ name: 'desktop:generation-policy', order: 950, text: context => context.agent && this.owner(context.agent)
      ? `Controlled image generation. Use only ${GENERATE_IMAGE_TOOL} once for the user's requested image. If it fails, report the failure and stop. Never use skills, processes, MCP, delegation, alternate providers, credentials, or balance queries. The user can leave this mode with /generation off.`
      : `For AI image generation use /image or the ${GENERATE_IMAGE_TOOL} controlled capability. A selected chat provider does not authorize a different AI service or credential. Do not use external AI CLIs as a fallback.` })
    ctx.inject(['commands'], commandCtx => {
      commandCtx.commands.register({ name: 'image', description: 'Generate an image using only the configured route for the selected provider', input: { hint: '<image description>' }, handler: ({ agent, rawInput, signal }) => {
        signal.throwIfAborted()
        if (!rawInput.trim()) return { kind: 'error', text: 'Enter an image description after /image.' }
        if (agent.status !== 'idle') return { kind: 'error', text: 'Wait for the current task to finish or stop it before starting controlled generation.' }
        this.enable(agent)
        try { snapshotGenerationRoute(selectedGenerationChat(ctx, agent).provider, this.routes()) }
        catch (cause) { return { kind: 'error', text: cause instanceof GenerationError ? cause.message : 'Image route is unavailable.' } }
        agent.followup(createUserMessage({ source: { kind: 'user' }, content: [{ type: 'text', text: rawInput.trim() }] }))
        return { kind: 'success', text: 'Controlled generation enabled. Only the configured provider route is allowed. /generation off returns to ordinary Agent tools.' }
      } })
      commandCtx.commands.register({ name: 'generation', description: 'Control image generation tool isolation', input: { hint: '[on|off]' }, handler: ({ agent, rawInput }) => {
        if (agent.status !== 'idle') return { kind: 'error', text: 'Stop or finish the current task before changing generation mode.' }
        const command = rawInput.trim()
        if (command !== 'on' && command !== 'off') return { kind: 'success', text: this.owner(agent) ? 'Controlled generation is on. /generation off restores ordinary Agent tools and their network access.' : 'Controlled generation is off. /generation on restricts this session to the selected image route.' }
        if (command === 'on') this.enable(agent)
        else this.disable(agent)
        return { kind: 'success', text: command === 'on' ? 'Controlled generation enabled; unreviewed tools are denied.' : 'Ordinary Agent tools restored. Their process/network access follows your usual permission settings.' }
      } })
    })
    ctx.effect(() => () => {
      this.disposed = true
      for (const state of this.liveStates) { state.task?.abort.abort(); state.lift?.() }
      this.liveStates.clear()
    }, 'desktop: generation policy lifetime')
    for (const agent of ctx.agents.list()) this.state(agent)
  }

  private state(agent: Agent): GenerationState {
    let state = this.states.get(agent)
    if (state) return state
    const last = agent.session.snapshotEvents().findLast(event => event.type === 'desktop/generation-mode')
    state = { active: last?.type === 'desktop/generation-mode' && last.data.active, inherited: last?.type === 'desktop/generation-mode' && last.data.inherited === true }
    this.states.set(agent, state)
    this.liveStates.add(state)
    if (state.active) state.lift = agent.ctx.tools.restrict({ allow: [GENERATE_IMAGE_TOOL] })
    return state
  }
  private owner(agent: Agent): Agent | undefined {
    for (const scope of scopeChainOf(agent)) if (this.states.get(scope as Agent)?.active) return scope as Agent
    const visited = new Set<Agent>()
    for (let candidate: Agent | undefined = agent; candidate && !visited.has(candidate);) {
      visited.add(candidate)
      if (this.state(candidate).active) return candidate
      const parent: Agent['id'] | undefined = candidate.session.header.parentSession
      candidate = parent ? this.ctx.agents.get(parent) : undefined
    }
    return undefined
  }
  private denial(exec: Readonly<ToolExecution>): string | undefined {
    if (!exec.agent) return exec.name === GENERATE_IMAGE_TOOL ? DENIAL : undefined
    const owner = this.owner(exec.agent)
    if (!owner) return exec.name === GENERATE_IMAGE_TOOL ? 'Use /image to authorize a controlled generation request first.' : undefined
    const task = this.states.get(owner)?.task
    if (owner !== exec.agent || this.state(exec.agent).inherited || exec.name !== GENERATE_IMAGE_TOOL || !task || task.used || task.signal.aborted || exec.signal.aborted || this.disposed) return DENIAL
    return undefined
  }
  enable(agent: Agent): void {
    const state = this.state(agent)
    if (state.active) return
    state.lift = agent.ctx.tools.restrict({ allow: [GENERATE_IMAGE_TOOL] })
    state.active = true
    agent.session.append('desktop/generation-mode', { active: true })
    for (const candidate of this.ctx.agents.list()) this.inherit(candidate)
  }
  private inherit(agent: Agent): void {
    const owner = this.owner(agent), state = this.state(agent)
    if (!owner || owner === agent || state.inherited) return
    state.active = true; state.inherited = true
    state.lift ??= agent.ctx.tools.restrict({ allow: [] })
    state.task?.abort.abort(); state.task = undefined
    agent.session.append('desktop/generation-mode', { active: true, inherited: true })
  }
  disable(agent: Agent): void {
    const state = this.state(agent)
    if (state.inherited || (this.owner(agent) !== agent && this.owner(agent))) throw new GenerationError('INHERITED_POLICY', 'A child cannot lift its parent generation policy.')
    state.task?.abort.abort()
    state.active = false; state.task = undefined; state.lift?.(); state.lift = undefined
    agent.session.append('desktop/generation-mode', { active: false })
  }
}
